{
  "formatVersion": "1.1",
  "component": {
    "group": "net.fabricmc",
    "module": "tiny-mappings-parser",
    "version": "0.3.0+build.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "h5wm4gi57jgqhcm7vndxt32xhi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tiny-mappings-parser-0.3.0+build.17.jar",
          "url": "tiny-mappings-parser-0.3.0+build.17.jar",
          "size": 82671,
          "sha512": "b105efe66ee8404d503db28f98f4b0c53efc04f218a1e115001080ea7c08dfeff38b37fb95757ce8261fc3ecf617007b511b995d3f371e78659f37d154695665",
          "sha256": "ab91038c4b1bff9b0999eb6959e012cd0e0bf116401ebab37001ec325d877ba6",
          "sha1": "02f10540a290e382a7cd35c16ec3900046a4e252",
          "md5": "2ecb50617a3a012062e53ca4cda50936"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tiny-mappings-parser-0.3.0+build.17.jar",
          "url": "tiny-mappings-parser-0.3.0+build.17.jar",
          "size": 82671,
          "sha512": "b105efe66ee8404d503db28f98f4b0c53efc04f218a1e115001080ea7c08dfeff38b37fb95757ce8261fc3ecf617007b511b995d3f371e78659f37d154695665",
          "sha256": "ab91038c4b1bff9b0999eb6959e012cd0e0bf116401ebab37001ec325d877ba6",
          "sha1": "02f10540a290e382a7cd35c16ec3900046a4e252",
          "md5": "2ecb50617a3a012062e53ca4cda50936"
        }
      ]
    }
  ]
}
